; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env]
monitor_speed = 115200
upload_speed = 921600
platform = https://github.com/platformio/platform-espressif32.git # stable version
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
;platform = https://github.com/pioarduino/platform-espressif32.git#develop

framework = arduino
; https://registry.platformio.org/tools/espressif/toolchain-riscv32-esp/versions
;platform_packages = espressif/toolchain-riscv32-esp
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
monitor_filters = esp32_exception_decoder
build_flags = 
    !python scripts/build_flags.py git_branch
    !python scripts/build_flags.py git_repo
    !python scripts/build_flags.py git_owner
    -D GITHUB_RUN=\"${sysenv.GITHUB_RUN}\"
;    -D WIFISSID=\"gast\"             ; use fixed WiFi credentials if Improv-WiFi-Library isn´t supported by your board
;    -D WIFIPASSWORD=\"12345678\"     ; use fixed WiFi credentials if Improv-WiFi-Library isn´t supported by your board

lib_ignore = 
    mbed-zrem/WiFi
    ayushsharma82/RPAsyncTCP

lib_deps = 
    https://github.com/tobiasfaust/Improv-WiFi-Library.git
    https://github.com/tobiasfaust/ElegantOTA.git
    https://github.com/tobiasfaust/esp-handlefiles.git
    https://github.com/tobiasfaust/webserial.git
    https://github.com/knolleary/pubsubclient
    https://github.com/bblanchon/ArduinoJson
    https://github.com/bblanchon/ArduinoStreamUtils
    https://github.com/YiannisBourkelis/Uptime-Library
    https://github.com/ESP32Async/ESPAsyncWebServer

custom_lib_deps_tb6612 =
    https://github.com/wemos/WEMOS_Motor_Shield_Arduino_Library
    
custom_lib_deps_i2c =
    https://github.com/tobiasfaust/i2cdetect   
    
custom_lib_deps_oled =
    https://github.com/ThingPulse/esp8266-oled-ssd1306
    
custom_lib_deps_pfc8574 =
    https://github.com/xreef/PCF8574_library

custom_lib_deps_onewire =
    https://github.com/PaulStoffregen/OneWire
    https://github.com/tobiasfaust/arduino-ds2408

custom_lib_deps_ads1115 =
    https://github.com/wollewald/ADS1115_WE

custom_lib_deps_BLE =
;    https://github.com/h2zero/NimBLE-Arduino@^2.1.0
;    using static library in folder libs/NimBLE-Arduino
;    use fixed NimBLE Lib v2.3.2, current v.2.3.6 doesn´t work (issue: h2zero/NimBLE-Arduino#1039)
;    h2zero/NimBLE-Arduino@^2.3.0
    h2zero/NimBLE-Arduino

extra_scripts = 
    pre:scripts/prepareDataDir.py

#####################################################################
[env:firmware_ESP32-Flowercare]
board = esp32dev
;board_build.partitions = min_spiffs.csv
lib_deps = ${env.lib_deps}
    ${env.custom_lib_deps_BLE}
    ${env.custom_lib_deps_tb6612}
    ${env.custom_lib_deps_i2c}
;lib_extra_dirs = libs
build_flags = ${env.build_flags}
    -D GIT_VARIANT=\"Flowercare\"
    -D USE_FLOWERCARE=1
    -D USE_TB6612=1
build_src_filter = +<*> -<ow2408.*> -<oled.*> -<pcf8574.*> -<ads1115.*> -<oneWire.*> -<flowcontrol.*> -<doif.*>

###################################
[env:firmware_ESP32]
board = esp32dev
lib_deps = ${env.lib_deps}
    ${env.custom_lib_deps_pfc8574}
    ${env.custom_lib_deps_tb6612}
    ${env.custom_lib_deps_i2c}
    ${env.custom_lib_deps_onewire}
    ${env.custom_lib_deps_oled}
    ${env.custom_lib_deps_ads1115}
build_flags = ${env.build_flags}
    -D GIT_VARIANT=\"Standard\"
    -D USE_PCF8574=1
    -D USE_TB6612=1
    -D USE_ONEWIRE=1
    -D USE_OLED=1
    -D USE_ADS1115=1
    -D USE_FLOWCONTROL=1
    -D USE_DOIF=1
;    -DSERIAL_TX_BUFFER_SIZE=1536
;    -DSERIAL_RX_BUFFER_SIZE=512
;    -DCONFIG_ETH_DMA_BUFFER_SIZE=512
;    -DCONFIG_ETH_DMA_TX_BUFFER_NUM=1536
;    -DCONFIG_ETH_DMA_RX_BUFFER_NUM=512
build_src_filter = +<*> -<flowercare.*>

###################################
[env:firmware_ESP32-S2]
board = esp32-s2-saola-1
lib_deps = ${env.lib_deps}
    ${env.custom_lib_deps_pfc8574}
    ${env.custom_lib_deps_tb6612}
    ${env.custom_lib_deps_i2c}
    ${env.custom_lib_deps_onewire}
    ${env.custom_lib_deps_oled}
    ${env.custom_lib_deps_ads1115}
build_flags = ${env.build_flags}
    -D GIT_VARIANT=\"Standard\"
    -D USE_PCF8574=1
    -D USE_TB6612=1
    -D USE_ONEWIRE=1
    -D USE_OLED=1
    -D USE_ADS1115=1
    -D USE_FLOWCONTROL=1
    -D USE_DOIF=1
build_src_filter = +<*> -<flowercare.*>

###################################
[env:firmware_ESP32-S3]
board = esp32-s3-devkitc-1
lib_deps = ${env.lib_deps}
    ${env.custom_lib_deps_pfc8574}
    ${env.custom_lib_deps_tb6612}
    ${env.custom_lib_deps_i2c}
    ${env.custom_lib_deps_onewire}
    ${env.custom_lib_deps_oled}
    ${env.custom_lib_deps_ads1115}
build_flags = ${env.build_flags}
    -D GIT_VARIANT=\"Standard\"
    -D USE_PCF8574=1
    -D USE_TB6612=1
    -D USE_ONEWIRE=1
    -D USE_OLED=1
    -D USE_ADS1115=1
    -D USE_FLOWCONTROL=1
    -D USE_DOIF=1
build_src_filter = +<*> -<flowercare.*>

###################################
[env:firmware_ESP32-C3]
board = esp32-c3-devkitm-1
lib_deps = ${env.lib_deps}
;    ${env.custom_lib_deps_pfc8574}
;    ${env.custom_lib_deps_tb6612}
;    ${env.custom_lib_deps_i2c}
;    ${env.custom_lib_deps_onewire}
;    ${env.custom_lib_deps_oled}
;    ${env.custom_lib_deps_ads1115}
build_flags = ${env.build_flags}
    -D GIT_VARIANT=\"Standard\"
    -D ARDUINO_USB_MODE=1 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D USE_PCF8574=1
    -D USE_TB6612=1
    -D USE_ONEWIRE=1
    -D USE_OLED=1
    -D USE_ADS1115=1
    -D USE_FLOWCONTROL=1
    -D USE_DOIF=1
build_src_filter = +<*> -<flowercare.*>

###################################
[env:firmware_ESP8266]
platform = espressif8266
board = nodemcuv2
monitor_filters = esp8266_exception_decoder
lib_deps =
    ${env.lib_deps}
build_flags = 
    ${env.build_flags}
    -D GIT_VARIANT=\"Standard\"
build_src_filter = +<*> -<tb6612.*> -<ow2408.*> -<oled.*> -<pcf8574.*> -<ads1115.*> -<oneWire.*> -<i2cdetect.*> -<motor.*> -<flowercare.*> -<flowcontrol.*> -<doif.*>
